version: "3.1"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db-iabets-prd-cluster.coel50q1pqpk.us-east-1.rds.amazonaws.com
  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      PHP_MEMORY_LIMIT: -1
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/wc-pagarme-pix-payment
      - C:/Dev/Coding/woocommerce.9.0.2/woocommerce:/var/www/html/wp-content/plugins/woocommerce
      - C:/Dev/Projects/Other Clients/polopix/wc-polo-payments:/var/www/html/wp-content/plugins/wc-polo-payments
      - C:/Dev/Projects/Other Clients/intensivacursos/intensiva-cursos-checkout:/var/www/html/wp-content/plugins/intensiva-cursos-checkout
      - C:/Dev/Projects/Other Clients/abdiel/rd-station-integration:/var/www/html/wp-content/plugins/rd-station-integration
      - C:/Dev/Coding/plugins-de-terceiros/funnel-builder-pro/funnel-builder-pro:/var/www/html/wp-content/plugins/funnel-builder-pro
      - C:/Dev/Coding/plugins-de-terceiros/learndash/sfwd-lms:/var/www/html/wp-content/plugins/sfwd-lms
      - C:/Dev/Coding/plugins-de-terceiros/learndash-woocommerce/learndash-woocommerce:/var/www/html/wp-content/plugins/learndash-woocommerce
      - C:/Dev/Projects/Other Clients/intensivacursos/woocommerce-pagarme-3.0.0/woocommerce-pagarme:/var/www/html/wp-content/plugins/woocommerce-pagarme
  db:
    image: mysql:5.7
    restart: always
    container_name: wordpress_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
